### ISSUE TITLE
xypattern==1.0.4 cannot be installed from source

### ISSUE THREAD

**Issue by t20100** [CPrescher/xypattern#1]
Related to https://github.com/Dioptas/Dioptas/issues/173

`xypattern` cannot be installed from source: `pip install --no-deps --no-cache xypattern --no-binary xypattern` leads to `RuntimeError: This does not appear to be a Git project`.

<details><summary>Logs</summary>

```
Collecting xypattern
  Downloading xypattern-1.0.4.tar.gz (11 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Traceback (most recent call last):
        File "testenv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "testenv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "testenv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-i76nvbba/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 42, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
        File "/tmp/pip-build-env-i76nvbba/overlay/lib/python3.10/site-packages/poetry_dynamic_versioning/patch.py", line 26, in alt_poetry_create
          name = _get_and_apply_version(
        File "/tmp/pip-build-env-i76nvbba/overlay/lib/python3.10/site-packages/poetry_dynamic_versioning/__init__.py", line 485, in _get_and_apply_version
          version = _get_version(config, name)
        File "/tmp/pip-build-env-i76nvbba/overlay/lib/python3.10/site-packages/poetry_dynamic_versioning/__init__.py", line 312, in _get_version
          version = _get_version_from_dunamai(vcs, pattern, config)
        File "/tmp/pip-build-env-i76nvbba/overlay/lib/python3.10/site-packages/poetry_dynamic_versioning/__init__.py", line 264, in _get_version_from_dunamai
          return Version.from_vcs(
        File "/tmp/pip-build-env-i76nvbba/overlay/lib/python3.10/site-packages/dunamai/__init__.py", line 1934, in from_vcs
          return cls._do_vcs_callback(
        File "/tmp/pip-build-env-i76nvbba/overlay/lib/python3.10/site-packages/dunamai/__init__.py", line 1973, in _do_vcs_callback
          return callback(**kwargs)
        File "/tmp/pip-build-env-i76nvbba/overlay/lib/python3.10/site-packages/dunamai/__init__.py", line 1066, in from_git
          _detect_vcs(vcs, path)
        File "/tmp/pip-build-env-i76nvbba/overlay/lib/python3.10/site-packages/dunamai/__init__.py", line 355, in _detect_vcs
          raise RuntimeError(
      RuntimeError: This does not appear to be a Git project
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

</details>

**Comment by CPrescher** [comment]
Thanks for pointing this out. This is now working with 1.0.5. I added the poetry-dynamic-versioning during the CD github Action:

```yaml
      - name: Add Dynamic Versioning Plugin
        run: poetry self add poetry-dynamic-versioning[plugin]
```
